"""Add MPRRecord and Project last columns

Revision ID: 850ee1e128af
Revises: 
Create Date: 2026-05-02 08:39:04.490645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '850ee1e128af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('current_tier', sa.String(), nullable=False),
    sa.Column('tier_entered_date', sa.String(), nullable=False),
    sa.Column('tier_deadline', sa.String(), nullable=True),
    sa.Column('responsible_party', sa.String(), nullable=True),
    sa.Column('next_action', sa.String(), nullable=True),
    sa.Column('clause', sa.String(), nullable=True),
    sa.Column('notice_text', sa.String(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_events_event_id'), 'escalation_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_escalation_events_id'), 'escalation_events', ['id'], unique=False)
    op.create_index(op.f('ix_escalation_events_project_id'), 'escalation_events', ['project_id'], unique=False)
    op.create_table('mpr_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('reporting_period', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('actual_physical_pct', sa.Float(), nullable=True),
    sa.Column('planned_physical_pct', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_label', sa.String(), nullable=True),
    sa.Column('total_ld_accrued_inr', sa.Float(), nullable=True),
    sa.Column('critical_event_count', sa.Integer(), nullable=True),
    sa.Column('high_event_count', sa.Integer(), nullable=True),
    sa.Column('total_event_count', sa.Integer(), nullable=True),
    sa.Column('exec_data_json', sa.JSON(), nullable=True),
    sa.Column('compliance_json', sa.JSON(), nullable=True),
    sa.Column('risk_json', sa.JSON(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('uploaded_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpr_records_id'), 'mpr_records', ['id'], unique=False)
    op.create_index(op.f('ix_mpr_records_project_id'), 'mpr_records', ['project_id'], unique=False)
    op.drop_index(op.f('ix_clause_embeddings_contract_id'), table_name='clause_embeddings')
    op.drop_index(op.f('ix_clause_embeddings_id'), table_name='clause_embeddings')
    op.drop_table('clause_embeddings')
    op.add_column('projects', sa.Column('last_risk_score', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('last_risk_label', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('last_ld_accrued_inr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_ld_accrued_inr')
    op.drop_column('projects', 'last_risk_label')
    op.drop_column('projects', 'last_risk_score')
    op.create_table('clause_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clause_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clause_embeddings_pkey'))
    )
    op.create_index(op.f('ix_clause_embeddings_id'), 'clause_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_clause_embeddings_contract_id'), 'clause_embeddings', ['contract_id'], unique=False)
    op.drop_index(op.f('ix_mpr_records_project_id'), table_name='mpr_records')
    op.drop_index(op.f('ix_mpr_records_id'), table_name='mpr_records')
    op.drop_table('mpr_records')
    op.drop_index(op.f('ix_escalation_events_project_id'), table_name='escalation_events')
    op.drop_index(op.f('ix_escalation_events_id'), table_name='escalation_events')
    op.drop_index(op.f('ix_escalation_events_event_id'), table_name='escalation_events')
    op.drop_table('escalation_events')
    # ### end Alembic commands ###
