"""change MPRRecord.created_at to datetime

Revision ID: b49dcac55fe5
Revises: 850ee1e128af
Create Date: 2026-05-02 13:57:48.938085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b49dcac55fe5'
down_revision: Union[str, Sequence[str], None] = '850ee1e128af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clause_embeddings_contract_id'), table_name='clause_embeddings')
    op.drop_index(op.f('ix_clause_embeddings_id'), table_name='clause_embeddings')
    op.drop_table('clause_embeddings')
    op.alter_column('mpr_records', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='created_at::timestamp without time zone')
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'contract_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'scp_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'contract_value_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.drop_column('projects', 'appointed_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('appointed_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.alter_column('projects', 'contract_value_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('projects', 'scp_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'contract_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mpr_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('clause_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clause_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clause_embeddings_pkey'))
    )
    op.create_index(op.f('ix_clause_embeddings_id'), 'clause_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_clause_embeddings_contract_id'), 'clause_embeddings', ['contract_id'], unique=False)
    # ### end Alembic commands ###
